apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: identity-server-secrets-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: identity-server-secrets
  data:
  - secretKey: ConnectionStrings__IdentityConnection
    remoteRef:
      key: secrets-k8/identity/{{ .Values.env_name }}/connections
      property: connectionstring
  - secretKey: ProviderSettings__GoogleClientId
    remoteRef:
      key: secrets-k8/identity/{{ .Values.env_name }}/providers/google
      property: clientid
  - secretKey: ProviderSettings__GoogleClientSecret
    remoteRef:
      key: secrets-k8/identity/{{ .Values.env_name }}/providers/google
      property: clientsecret