stages:
- template: stages/stages-generate-commit-manifests/v1.yml@templates
  parameters:
    environmentName: "test"
    helmfileDirectory: ./
    argoRepoName: ops_nonprod_cluster
    argoBaseDir: apps/identity
    helmfileVersion: "1.1.5"
