stages:
- template: stages/stages-generate-commit-manifests/v1.yml@templates
  parameters:
    kubernetesConnectionName: "k8-nonprod"
    environmentName: "test"
    namespace: "test"
    helmfileDirectory: ./
    argoRepoName: ops_nonprod_cluster
    argoBaseDir: apps/identity
