resources:
  repositories:
    - repository: ops_nonprod_cluster
      type: BitBucket
      endpoint: Bitbucket - spydersoft
      name: spydersoftteam/ops-nonprod-cluster
    - repository: ops_prod_cluster
      type: BitBucket
      endpoint: Bitbucket - spydersoft
      name: spydersoftteam/ops-prod-cluster
    - repository: templates
      type: BitBucket
      endpoint: "Bitbucket - spydersoft"
      name: spydersoftteam/azure-devops-templates

trigger:
  batch: true
  branches:
    include:
    - main 
    - feature/*
  paths:
    exclude:
    - README.md
    - scripts/*

pr: none

extends:
  ${{ if contains(variables['Build.SourceBranch'], 'main') }}:
    template: release.yml
  ${{ if not(contains(variables['Build.SourceBranch'], 'main')) }}:
    template: feature.yml

